name: heathen_match
description: A Tinder-like app tailored specifically for atheists
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.4
  flutter_tindercard: ^0.2.0
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
