name: HeathenMatch
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^1.10.0"
  cloud_firestore: "^3.1.0"
  firebase_auth: "^3.3.0"
  provider: ^6.0.1
  flutter_tindercard: ^1.3.3
